### PR TITLE
Improved Dockerfiles

### PR DESCRIPTION
**Pull request by hunterdp**
## What
Created separate Dockerfiles for supported operating systems.

## Why
Enable it to be easier to maintain and modify for future SDK versions.

## How
- Added a Dockerfile for Rocky Linux.
- Added Groq API repository clone as well.
- Shifted to install under the user *groq*.
- Added *groq* user to the sudoer list.
- Modified the top level README.md file.
- Modified the docker/readme.md file to accommodate the multiple Dockerfiles and present a standard naming and tagging convention.

## Testing
I tested this multiple times on local machines for Ubuntu 22.04, Rocky 84 and Rocky 8.5 over multiple days.  The host:
```
OS: Rocky Linux 9.2 (Blue Onyx) x86_64
Host: HP Z230 Tower Workstation
Kernel: 5.14.0-284.30.1.el9_2.x86_64
Packages: 1964 (rpm), 9 (flatpak)
Shell: bash 5.1.8
Terminal: /dev/pts/1
CPU: Intel Xeon E3-1225 v3 (4) @ 3.600GHz [34.0°C]
GPU: NVIDIA GeForce GTX 950
GPU: Intel HD Graphics
Memory: 5828MiB / 31521MiB
```

## Anything Else
I want to add another Dockerfile support for RHEL, but that was not working yet.

### CODE REVIEW

**Comment by hunterdp** [comment]
This commit modifies the Dockerfile to:
- Be easier to update with new SDK releases
- Adds a separate Dockerfile for Rocky Linux
- Updates the READMe and docker/readme files.

**Comment by settle-groq** [comment]
@hunterdp The Ubuntu image successfully built for me, but the Rocky one ran into the following error:
`Step 18/30 : RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 ---> Running in 4b01480da82c
miniconda.sh: Permission denied
The command '/bin/sh -c wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh' returned a non-zero code: 1
`

I typically don't create users and mess with sudo within docker images, or expose ports from within the dockerfile itself.  I tend to leave that up to the end user of the docker file if that's what they wish to do.  But I have no hard preference, just following the example of another popular vendor.

**Comment by hunterdp** [comment]
@settle-groq I just rebuilt it successfully again multiple times with no issues.  I have not seen that error and cannot reproduce it in my environment.   Try adding the --network=host on the build command line. 

As to non-root containers, I prefer that vs running everything as root.   As commented in the Dockerfiles, the user can comment this out and run without sudoer. The experienced docker folks will change to what they desire in my experience.

I can go either way on building the exposed ports in the Dockerfile,

**Comment by settle-groq** [comment]
@hunterdp Looks like the root error above wasn't related to the network=host but was caused by a reported issue with my docker version
`$ docker --version                                                                                                                 
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3`

What was happening was in my docker version it created the "groq" user with "root:root" ownership, so the "groq" user couldn't download the miniconda.sh in that home directory.

If I prepended `DOCKER_BUILDKIT=1` to the build command then it successfully completed, and also tested a few of the pytorch example models within the container.

**Review by settle-groq — APPROVED** [review]
Looks good.

**Pull request merged**
